apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: ml-detector-quay-build
  namespace: ebpf-security
spec:
  serviceAccountName: tekton-builder-sa
  pipelineRef:
    name: application-build-ci
  params:
    - name: git-url
      value: https://github.com/jeanlopezxyz/ebpf-ia-kubernetes.git
    - name: git-revision
      value: main
    - name: image-registry
      value: quay.io/jealopez
    - name: image-name
      value: ml-detector
    - name: dockerfile-path
      value: applications/ml-detector/Dockerfile
    - name: context-path
      value: applications/ml-detector
    - name: argo-app-name
      value: ebpf-ai
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: local-path
    - name: dockerconfig
      secret:
        secretName: quay-io-secret