[tool.black]
line-length = 88
target-version = ["py311"]
skip-string-normalization = true

[tool.ruff]
line-length = 88
target-version = "py311"
extend-select = ["E","F","I","UP","B","SIM","PL"]
ignore = [
  # Allow prints/logging styles as per project conventions
]
exclude = [
  ".venv",
  "notebooks",
  "build",
  "dist",
]

