apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-secret
  namespace: ebpf-security
  labels:
    app.kubernetes.io/name: tekton-webhook
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: ebpf-ai-system
type: Opaque
stringData:
  secretToken: "webhook-secret-token-2024"