apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Install before other apps
spec:
  project: default
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: 2.13.3
    helm:
      values: |
        fullnameOverride: sealed-secrets-controller
        
        controller:
          create: true
          secretName: "sealed-secrets-key"
          
        serviceAccount:
          create: true
          name: sealed-secrets-controller
          
        rbac:
          create: true
          
        # Security context
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          fsGroup: 65534
          
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
            
        # Node affinity to run on control plane if needed
        nodeSelector: {}
        tolerations: []
        
        # Service configuration
        service:
          type: ClusterIP
          port: 8080
          
        # Enable metrics
        metrics:
          serviceMonitor:
            enabled: false  # Set to true if Prometheus operator is installed
            
        # Log level
        logLevel: info
        
        # Additional arguments
        additionalNamespaces: []
        
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m