apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-pipelines-custom
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jeanlopezxyz/ebpf-ia-kubernetes.git
    path: gitops/pipelines
    targetRevision: main
    directory:
      include: "*.yaml"
      exclude: "*run*.yaml"  # Exclude pipeline runs, only templates
  destination:
    server: https://kubernetes.default.svc
    namespace: ebpf-security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true