apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-triggers
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Install with base Tekton
spec:
  project: default
  source:
    repoURL: https://github.com/jeanlopezxyz/ebpf-ia-kubernetes.git
    path: gitops/tekton-triggers-base
    targetRevision: main
    directory:
      include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-pipelines
  syncPolicy:
    automated:
      prune: false  # Don't prune to avoid conflicts with existing installation
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 1m
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true