apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-rbac-additional
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # After Tekton Triggers base
spec:
  project: default
  source:
    repoURL: https://github.com/jeanlopezxyz/ebpf-ia-kubernetes.git
    path: gitops/tekton-rbac
    targetRevision: main
    directory:
      include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true