apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton
  namespace: argocd
  labels:
    app.kubernetes.io/name: tekton
    app.kubernetes.io/part-of: ebpf-ai-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jeanlopezxyz/ebpf-ia-kubernetes.git
    targetRevision: main
    path: helm/charts/infra-kube-tekton
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true