apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-resources
  namespace: argocd
  labels:
    app.kubernetes.io/name: tekton-resources
    app.kubernetes.io/part-of: ebpf-ai-platform
    app.kubernetes.io/component: ci-cd-resources
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jeanlopezxyz/ebpf-ia-gitops.git
    targetRevision: main
    path: gitops/tekton-resources
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ebpf-security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  ignoreDifferences:
    # Ignore dynamic Cilium resources that are managed by Cilium operator
    - group: cilium.io
      kind: CiliumIdentity
      jsonPointers:
        - /metadata
        - /security-labels
    - group: cilium.io  
      kind: CiliumEndpoint
      jsonPointers:
        - /metadata
        - /status