apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-admin-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/part-of: ebpf-ai-platform
    app.kubernetes.io/component: secret
spec:
  encryptedData:
    # admin:oSsMYDYPSzcXXexpW2GdSrM2g
    admin-password: AgAHZfNO3...  # Encrypted password here
    admin-user: AgBsY2...         # Encrypted username here
  template:
    metadata:
      name: argocd-admin-secret
      namespace: argocd
      labels:
        app.kubernetes.io/name: argocd
        app.kubernetes.io/part-of: ebpf-ai-platform
    type: Opaque