apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-webhook-secret
  namespace: tekton
  labels:
    app.kubernetes.io/name: tekton-triggers
    app.kubernetes.io/part-of: ebpf-ai-platform
    app.kubernetes.io/component: secret
spec:
  encryptedData:
    # webhook-secret:2N1ydZkoZ1iuZPHn5mnI0A8bK
    webhook-secret: AgDfH8...      # Encrypted webhook secret here
  template:
    metadata:
      name: github-webhook-secret
      namespace: tekton
      labels:
        app.kubernetes.io/name: tekton-triggers
        app.kubernetes.io/part-of: ebpf-ai-platform
    type: Opaque