apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgBRv7YqmQMpTV3kCr+1DGhqZk085sZa0686I33GK6WFw6HnS/8Sg3KJbh7+GrHH7ecSaPCRlU4yBNZgsjcOT1C6GuwOS/95P6Fkxn8DQgl8peQ6chrW1YY9kytlRcQnbC8qfV38LH1UNx+NoringoHF+5t5YvQSOQiRf+k7LnxMNlRlrLRswcJ8S5bSdYGBDTy52EMMeyi0FDDv6lwCpAa45Y6P9S59+WaGd5AgQ3LwFAWw0NJsiDhX15MrHsY6DqHstr8G9Jz5Iz4L/0dPzw8RFQIu48Qpj9/geBZKxUCRTWG4UPOr12A3FFKPVrOAJSOjvQ+ro/T+d3WL8Jay41hn7QzuXtF7XGabiOKO9gHEHRGM0QsrfDOjkzfwkHmarU47Xo8Ci/GWM+9y+B4MhPUAt309xggtjx1tYgQ96/5TYU4NHspZ3zjuiIRHQ6XqoB5+tVV6SSFbZwM040LKJFgJAMxiUIB6yP8b4bH5a/i7YhNue3AiaQNAZTCbNFKE6cyzF8utAYKpXF/WRFYPNz0qmpn7a2RD5wMpuFwzC/x1iDna+hnEtqAXf+Ltozb3h6gMbGYCEZi2f5ktPH3gD4q/73zTziOATH2LTjgDEQ7cjMZdVW+a2vuAoe+SVCalNV2nPOMZH+EG6BJppjQHmK6x20/UqsgTppokeL8jxBFopphx+Z6Vy0JOQhmEumZjw8RfYU1m8hw1g4mpHxr189jP0+zIRJzz7LuT
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: grafana
---
