apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: quay-io-secret
  namespace: ebpf-security
spec:
  encryptedData:
    .dockerconfigjson: AgB60B9OprFKT4l6vdQeXd7saauinezRgY6C4JRl41hnmivWYQ1iOgtyWedkFMocgNX2hqKgaIQtrlyXWE2QqCp5aQcXmfgeHRRMenCoumBxWl5FSfOAloqFTZSlteqQJq5wDPa6NAnQB6TC2GtjNy4MyGuV6wS5jjaErk5157eotxaBz3joJvGyXGDsHyCfFG95m/bgqmRPK8hx0gjnUUQTz40Jp7j9gEBMoC5PE2yAljyWjFclgdK2P/32Bf8LrlzahR/E1efQQlBZTLDHRjmid8b5w1lXVDRzc/q1ugVjKGUf6ck55gm1NC9n5Rx5Hdu2MPAuyFQ0W8vuh+IyrvSTsU1rZ8wWOMNkIqrcpEe9AI2rdEavpBXNiTq1ISYY7OZ4IxlXIabqgv/AqLWdpC9K+xfFjevc2LArnTuFJUwVP5muLhzSx//HieC3/nazmoT/m+ciMZ7rqBomT3ceWjcMot4FVOIlr14GQDyVsHoXNfX7v8wvlWKkqRlQd0BasR8aQdJXDv9p9btbnfMTLXkItBoN+yFrOXabV1EXCYFYPLMjCmzQL9/C6blk/Ze20g9G1zGecfVEjuicAmX+7TXlMQctF2I9DZaIX5VniIIxOV4O29zLEOTjn0A3kDCyQGxlRFUPE3XrUkFRq12tL5gSFmcK6RdJIiVJBb33LvujznhBcSp5UjYRn8HXKq0Nm2pf88t5yRmLSP3l1DCLZ8vK3B4ytapn6vpEUTcgC1Z+bw0HUx9RAjfhmjmDdmVvlw0736juDiuAoNiyEDt0vcb7isI6X9c7aHpY3WxRBHHVpXVXPi925VMMDlC/m4BIJqs9mkZYRLCAiBNCFscYnervusIsjSa+W50v0We62PoXSQNcUX2gp4gTCPnZm/Z2/uNs1Vb2t95UvO1NWW5IJMCRVo/mrY9xdfToJMaTOl/rxDLkFBLSFY13V0Y/cQH226XR63V/OeW4cKSjeg6l5C8C3sGcGnj7vLh1GfwoaEnOJYx6vHbNW3sVA+SVyoeGE1Lz5Uk=
  template:
    metadata:
      creationTimestamp: null
      name: quay-io-secret
      namespace: ebpf-security
    type: kubernetes.io/dockerconfigjson
---
