---
# Global configuration for eBPF + AI GitOps deployment

# Environment configuration
#
# LAB MODE (default):
#   - Uses NodePort for services (accessible via node IP + port)
#   - Uses podman driver (simpler setup)
#   - Access: http://node-ip:nodeport
#
# PROD MODE:
#   - Uses NodePort with external load balancer (pfSense)
#   - Uses qemu driver with bridge networking
#   - Real network IPs (10.0.10.x range)
#   - Access: http://external-lb-ip (direct)
#   - Requires: External load balancer configuration
#
deployment_mode:
  type: "prod" # Using prod mode with external load balancer (pfSense)
  external_lb: true # Use external load balancer (pfSense HAProxy)

# Cluster deployment method
cluster_method: "kubeadm" # Using kubeadm with KVM for production-like setup

# Kubeadm single-node configuration
kubeadm:
  node_name: "labjp"
  hostname: "api.k8s.labjp.xyz" # DNS hostname for API server
  base_domain: "apps.k8s.labjp.xyz" # Base domain for applications
  kubernetes_version: "v1.33.1" # Latest stable Kubernetes version (August 2025)
  pod_network_cidr: "10.244.0.0/16" # Pod network (65K IPs)
  service_cidr: "10.96.0.0/12" # Service network (1M IPs)
  vm:
    memory: "12288" # 12GB RAM
    cpus: 4
    disk_size: "60g"
    network_bridge: "br0" # Bridge network
    static_ip: "10.0.10.100" # Fixed IP for VM/API
    gateway: "10.0.10.1" # Bridge gateway
    dns_servers:
      - "10.0.10.1" # pfSense as primary DNS
      - "8.8.8.8" # Backup DNS

# Network configuration
network:
  # Production: External load balancer handles IP assignment
  # Lab: Use NodePort for external access
  bridge_interface: "br0" # Your configured bridge interface
  # Inside the Kubernetes node/VM, the NIC name that faces the 10.0.10.0/24 network
  # Example values: enp1s0, ens3, eth0 (use `ip -br -4 addr` on the node to confirm)
  node_interface: "enp1s0"


# Cilium configuration
cilium:
  version: "1.18.1" # Latest stable version (August 2025)
  enable_hubble: true
  enable_gateway_api: true
  enable_l2_announcements: false # Disabled for stability
  enable_netkit: false # Disabled for stability

# ArgoCD namespace (full config in helm/charts/argocd/)
argocd:
  namespace: "argocd"

# Application configuration
applications:
  ebpf_ai:
    namespace: "ebpf-security"
    git_repo: "https://github.com/jeanlopezxyz/ebpf-ia-gitops.git"
    git_path: "helm/charts/ebpf-ai"
    git_branch: "main"

# Ingress configuration
ingress:
  enabled: true
  nginx:
    enable_metrics: true
    ssl_redirect: false
    # Service type - NodePort for external load balancer compatibility
    service_type: "{{ 'NodePort' if deployment_mode.external_lb | default(false) else ('LoadBalancer' if deployment_mode.type == 'prod' else 'NodePort') }}"
  hosts:
    main: "ebpf-ai.apps.k8s.labjp.xyz"
    registry: "registry.apps.k8s.labjp.xyz"
    grafana: "grafana.apps.k8s.labjp.xyz"
    prometheus: "prometheus.apps.k8s.labjp.xyz"
    argocd: "argocd.apps.k8s.labjp.xyz"
    dashboard: "dashboard.apps.k8s.labjp.xyz"

# Resource limits
resources:
  ml_detector:
    replicas: 2
    cpu_limit: "1000m"
    memory_limit: "2Gi"
  ebpf_monitor:
    cpu_limit: "500m"
    memory_limit: "1Gi"
