# GolangCI-Lint configuration for eBPF Monitor
run:
  timeout: 5m
  go: "1.21"

linters-settings:
  gocyclo:
    min-complexity: 15
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/jeanlopezxyz/ebpf-ia-gitops
  
  govet:
    enable-all: true
  
  misspell:
    locale: US

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - goconst
    - gocyclo
    - unparam
  
  disable:
    - structcheck # deprecated
    - varcheck   # deprecated
    - deadcode   # deprecated

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    
    - text: "weak cryptographic primitive"
      linters:
        - gosec
