---
- name: Add Cilium Helm repository
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/

- name: Install Cilium CNI via Helm
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium
    chart_version: "{{ cilium.version }}"
    release_namespace: kube-system
    values:
      # Hubble observability (simplified)
      hubble:
        enabled: "{{ cilium.enable_hubble }}"
        relay:
          enabled: "{{ cilium.enable_hubble }}"
        ui:
          enabled: "{{ cilium.enable_hubble }}"
      # Gateway API support
      gatewayAPI:
        enabled: "{{ cilium.enable_gateway_api }}"
      # Enable eBPF-based kube-proxy replacement
      kubeProxyReplacement: true
      # Pod CIDR configuration
      ipam:
        mode: kubernetes
      # Simplified for stability
      operator:
        replicas: 1
    wait: true
    timeout: 600s

- name: Wait for Cilium DaemonSet to be ready
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: kube-system
    label_selectors:
      - k8s-app=cilium
    wait: true
    wait_condition:
      type: Ready
      status: "True"
    wait_timeout: 600

# Cilium CLI installation removed - CNI works perfectly without CLI

- name: Display Cilium status
  debug:
    msg:
      - "Cilium CNI v{{ cilium.version }} with eBPF installed successfully!"
      - "Hubble observability: {{ 'Enabled' if cilium.enable_hubble else 'Disabled' }}"
      - "Gateway API: {{ 'Enabled' if cilium.enable_gateway_api else 'Disabled' }}"
      - "L2 Announcements: {{ 'Enabled' if cilium.enable_l2_announcements else 'Disabled' }}"
      - "Netkit Datapath: {{ 'Enabled' if cilium.enable_netkit else 'Disabled' }}"
      - "eBPF Host Firewall: Enabled"
      - "kube-proxy replacement: Strict eBPF mode"
      - "Enhanced metrics: DNS, TCP, HTTP, Flow tracking"
