---
# Storage configuration for kubeadm clusters
# Using local-path-provisioner (Rancher)

- name: Install local-path-provisioner for kubeadm
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: local-path-storage
    state: present

- name: Deploy local-path-provisioner
  kubernetes.core.k8s:
    state: present
    src: https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.30/deploy/local-path-storage.yaml

- name: Wait for local-path-provisioner to be ready
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: local-path-provisioner
    namespace: local-path-storage
    wait: true
    wait_condition:
      type: Progressing
      status: "True"
    wait_timeout: 120

- name: Create default StorageClass for kubeadm
  kubernetes.core.k8s:
    definition:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: local-path
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
      provisioner: rancher.io/local-path
      volumeBindingMode: WaitForFirstConsumer
      reclaimPolicy: Delete
      allowVolumeExpansion: true
    state: present

- name: Display storage setup results
  debug:
    msg:
      - "✅ Storage configuration completed!"
      - "📦 StorageClass: local-path (default)"
      - "🔧 Provisioner: rancher.io/local-path"
      - "📁 Storage path: /opt/local-path-provisioner"