apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-ci-clusterrolebinding
  labels:
    app.kubernetes.io/name: tekton-ci
    app.kubernetes.io/part-of: ebpf-ai-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-ci-clusterrole
subjects:
  - kind: ServiceAccount
    name: tekton-ci-serviceaccount
    namespace: ebpf-security