apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: generate-tag
  namespace: ebpf-security
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: tekton-ci
    app.kubernetes.io/instance: tekton-ci
    app.kubernetes.io/component: task-generate-tag
    app.kubernetes.io/part-of: ebpf-ai-system
spec:
  workspaces:
    - name: source
  results:
    - name: image-tag
      description: Generated unique image tag
  steps:
    - name: generate
      image: alpine/git
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env sh
        set -eu
        if git rev-parse --short HEAD >/dev/null 2>&1; then
          SHORT_SHA=$(git rev-parse --short HEAD)
        else
          SHORT_SHA=unknown
        fi
        STAMP=$(date -u +%Y%m%d%H%M%S)
        NEW_TAG="sha-${SHORT_SHA}-${STAMP}"
        printf "%s" "$NEW_TAG" > $(results.image-tag.path)
