{{- if .Values.mlDetector.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.mlDetector.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.mlDetector.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ml-detector
    app.kubernetes.io/part-of: ebpf-ai
    # Label for Prometheus operator discovery
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.mlDetector.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - {{ .Values.global.namespace }}
{{- end }}