{{- if .Values.pipelines.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tekton-config
  namespace: {{ include "tekton.namespace" . }}
  labels:
    {{- include "tekton.labels" . | nindent 4 }}
data:
  registry-url: {{ .Values.tektonConfig.registry.url | quote }}
  registry-internal-url: {{ .Values.tektonConfig.registry.internal_url | quote }}
  git-repository: {{ .Values.tektonConfig.git.repository | quote }}
  git-branch: {{ .Values.tektonConfig.git.branch | quote }}
  webhook-host: {{ .Values.tektonConfig.webhook.host | quote }}
  dashboard-host: {{ .Values.tektonConfig.dashboard.host | quote }}
{{- end }}

{{- if .Values.dashboard.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tekton-dashboard
  namespace: {{ include "tekton.namespace" . }}
  labels:
    {{- include "tekton.dashboard.labels" . | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.tektonConfig.dashboard.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tekton-dashboard
            port:
              number: 9097
{{- end }}

{{- if .Values.triggers.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tekton-webhook
  namespace: {{ include "tekton.namespace" . }}
  labels:
    {{- include "tekton.labels" . | nindent 4 }}
    app.kubernetes.io/component: triggers
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.tektonConfig.webhook.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: el-tekton-listener
            port:
              number: 8080
{{- end }}