apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-secret
  namespace: tekton
type: Opaque
stringData:
  secretToken: "your-github-webhook-secret-here"  # Change this to a secure random string