apiVersion: v2
name: argocd
description: ArgoCD GitOps platform for eBPF-AI
version: 0.1.0
appVersion: "v2.9.3"
dependencies:
  - name: argo-cd
    version: "5.51.6"
    repository: https://argoproj.github.io/argo-helm