# ArgoCD Configuration for eBPF-AI Platform

argo-cd:
  configs:
    params:
      "server.insecure": "true" # HTTP mode for development
    cm:
      admin.enabled: "true"
      url: "http://argocd.apps.k8s.labjp.xyz" # External URL
    secret:
      argocdServerAdminPassword: "$2y$05$CwRbzWIwJRy0vAeVBjFhvOhaEceMwEl/2VQpJUqMotipPr00u1yiW"
      argocdServerAdminPasswordMtime: "2025-08-24T00:00:00Z"

  server:
    insecure: true
    service:
      type: "ClusterIP"  # ClusterIP with Ingress routing
    ingress:
      enabled: false # We use custom Ingress below
    extraArgs:
      - --insecure

  repoServer:
    env:
      - name: NO_PROXY
        value: "127.0.0.1,localhost,.svc,.cluster.local,kubernetes.default.svc"

# Ingress configuration for ArgoCD
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/client-body-timeout: "60"
    nginx.ingress.kubernetes.io/client-max-body-size: "1m"
  hosts:
    - host: argocd.apps.k8s.labjp.xyz
      paths:
        - path: /
          pathType: Prefix
          service:
            name: argocd-server
            port: 80
