# WEBHOOK AUTOMATION - Complete GitHub Integration
# EventListener + TriggerBinding + TriggerTemplate + RBAC + Ingress + Service

---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-webhook-listener
  namespace: ebpf-security
  labels:
    app.kubernetes.io/name: tekton-automation
    app.kubernetes.io/component: eventlistener
    app.kubernetes.io/part-of: ebpf-ai-system
spec:
  serviceAccountName: tekton-webhook-sa
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            serviceAccountName: tekton-webhook-sa
            containers:
            - resources:
                requests:
                  memory: "64Mi"
                  cpu: "100m"
                limits:
                  memory: "128Mi"
                  cpu: "200m"
  triggers:
    - name: ml-detector-webhook-trigger
      bindings:
        - ref: github-webhook-binding
      template:
        ref: ml-detector-webhook-template

---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-webhook-binding
  namespace: ebpf-security
  labels:
    app.kubernetes.io/name: tekton-automation
    app.kubernetes.io/component: triggerbinding
    app.kubernetes.io/part-of: ebpf-ai-system
spec:
  params:
    - name: git-revision
      value: $(body.head_commit.id)
    - name: git-repository-url
      value: $(body.repository.clone_url)
    - name: git-repository-name
      value: $(body.repository.name)
    - name: git-commit-message
      value: $(body.head_commit.message)

---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: ml-detector-webhook-template
  namespace: ebpf-security
  labels:
    app.kubernetes.io/name: tekton-automation
    app.kubernetes.io/component: triggertemplate
    app.kubernetes.io/part-of: ebpf-ai-system
spec:
  params:
    - name: git-revision
      default: main
    - name: git-repository-url
    - name: git-repository-name
      default: ebpf-ia-kubernetes
    - name: git-commit-message
      default: "Automated build"
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: webhook-automation-
        namespace: ebpf-security
        labels:
          app: ml-detector
          trigger: github-webhook
          git.commit: $(tt.params.git-revision)
        annotations:
          git.repository: $(tt.params.git-repository-url)
          git.message: $(tt.params.git-commit-message)
      spec:
        pipelineRef:
          name: application-build-ci
        taskRunTemplate:
          serviceAccountName: tekton-builder-sa
        params:
          - name: git-url
            value: $(tt.params.git-repository-url)
          - name: git-revision
            value: $(tt.params.git-revision)
          - name: image-registry
            value: quay.io/jealopez
          - name: image-name
            value: ml-detector
          - name: dockerfile-path
            value: applications/ml-detector/Dockerfile
          - name: context-path
            value: applications/ml-detector
          - name: argo-app-name
            value: ebpf-ai
        workspaces:
          - name: shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
                storageClassName: local-path
          - name: dockerconfig
            secret:
              secretName: quay-io-secret

---
# RBAC for webhook automation
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-webhook-sa
  namespace: ebpf-security
  labels:
    app.kubernetes.io/name: tekton-automation
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: ebpf-ai-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-webhook-eventlistener-binding
  namespace: ebpf-security
  labels:
    app.kubernetes.io/name: tekton-automation
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: ebpf-ai-system
subjects:
- kind: ServiceAccount
  name: tekton-webhook-sa
  namespace: ebpf-security
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-webhook-eventlistener-cluster
  labels:
    app.kubernetes.io/name: tekton-automation
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: ebpf-ai-system
subjects:
- kind: ServiceAccount
  name: tekton-webhook-sa
  namespace: ebpf-security
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles

---
# Webhook public exposure
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: github-webhook-ingress
  namespace: ebpf-security
  labels:
    app.kubernetes.io/name: tekton-automation
    app.kubernetes.io/component: ingress
    app.kubernetes.io/part-of: ebpf-ai-system
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: nginx
  rules:
  - host: webhook.apps.k8s.labjp.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: el-github-webhook-listener
            port:
              number: 8080

---
# NodePort service for webhook
apiVersion: v1
kind: Service
metadata:
  name: el-github-webhook-listener
  namespace: ebpf-security
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: github-webhook-listener
spec:
  type: NodePort
  ports:
    - name: http-listener
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30082
  selector:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: github-webhook-listener