---
- name: Get ArgoCD server service information
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Service
    name: argocd-server
    namespace: "{{ argocd.namespace }}"
  register: argocd_service_info
  
- name: Get Grafana service information
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Service
    name: ebpf-ai-grafana
    namespace: "{{ applications.ebpf_ai.namespace }}"
  register: grafana_service_info
  ignore_errors: yes
  
- name: Get ML Detector service information
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Service
    name: ml-detector
    namespace: "{{ applications.ebpf_ai.namespace }}"
  register: ml_detector_service_info
  ignore_errors: yes
  
- name: Display comprehensive access information
  debug:
    msg:
      - "🎉 eBPF + AI GitOps Environment Ready!"
      - ""
      - "🔧 INFRASTRUCTURE ACCESS:"
      - "   ArgoCD UI: https://argocd.apps.k8s.labjp.xyz"
      - "   ArgoCD CLI: argocd login argocd.apps.k8s.labjp.xyz --grpc-web"
      - "   Username: admin"
      - "   Password: [sealed-secret - check gitops/sealed-secrets/README.md]"
      - ""
      - "📊 APPLICATION ACCESS (External URLs):"
      - "   Grafana Dashboard: https://grafana.apps.k8s.labjp.xyz"
      - "   Backstage Portal: https://backstage.apps.k8s.labjp.xyz"
      - "   Kubernetes Dashboard: https://dashboard.apps.k8s.labjp.xyz"
      - "   Tekton Dashboard: https://tekton-dashboard.apps.k8s.labjp.xyz"
      - "   Registry: https://registry.apps.k8s.labjp.xyz"
      - "   ML Detector API: http://{{ ml_detector_service_info.resources[0].spec.clusterIP | default('Pending') }}:5000 (internal)"
      - ""
      - "🌐 EXTERNAL ACCESS:"
      - "   API Server: https://api.k8s.labjp.xyz:6443"
      - "   Webhook (CI/CD): https://tekton-webhook.apps.k8s.labjp.xyz"
      - ""
      - "🚀 QUICK COMMANDS:"
      - "   Monitor ArgoCD apps: argocd app list"
      - "   Sync application: argocd app sync ebpf-ai"
      - "   Port forward ArgoCD: kubectl port-forward svc/argocd-server -n argocd 8080:80"
      - "   Port forward Grafana: kubectl port-forward svc/ebpf-ai-grafana -n ebpf-security 3000:80"
      - ""
      - "📝 DEVELOPMENT WORKFLOW:"
      - "   1. Edit Helm charts in helm/charts/ebpf-ai/"
      - "   2. git add . && git commit -m 'Update config'"
      - "   3. git push origin main"
      - "   4. ArgoCD automatically syncs changes!"
      - ""
      - "🔍 MONITORING:"
      - "   Watch deployments: kubectl get pods -n ebpf-security -w"
      - "   Check ArgoCD logs: kubectl logs -n argocd -l app.kubernetes.io/name=argocd-application-controller"