backstage:
  image:
    repository: backstage/backstage
    tag: "1.31.0"

  backstage:
    appConfig:
      app:
        title: "eBPF + AI Developer Portal"
        baseUrl: http://backstage.apps.k8s.labjp.xyz
        
      backend:
        baseUrl: http://backstage.apps.k8s.labjp.xyz
        cors:
          origin: http://backstage.apps.k8s.labjp.xyz
        database:
          client: better-sqlite3
          connection: ':memory:'

      auth:
        providers:
          guest: {}

      techdocs:
        builder: local
        generators:
          techdocs: local
        publisher:
          type: local

      catalog:
        providers:
          github:
            providerId:
              organization: 'jeanlopezxyz'
              catalogPath: '/catalog-info.yaml'
              filters:
                branch: 'main'
        locations:
          - type: url
            target: https://github.com/jeanlopezxyz/ebpf-ia-kubernetes/blob/main/docs/catalog-info.yaml

      kubernetes:
        serviceLocatorMethod:
          type: multiTenant
        clusterLocatorMethods:
          - type: config
            clusters:
              - name: ebpf-ai-cluster
                url: https://api.k8s.labjp.xyz:6443
                authProvider: serviceAccount
                skipTLSVerify: true
                serviceAccountToken: ${KUBERNETES_SERVICE_ACCOUNT_TOKEN}

  postgresql:
    enabled: false

  extraEnvVars:
    - name: KUBERNETES_SERVICE_ACCOUNT_TOKEN
      valueFrom:
        secretKeyRef:
          name: backstage-secrets
          key: KUBERNETES_SERVICE_ACCOUNT_TOKEN

  envFrom:
    - secretRef:
        name: backstage-secrets

  ingress:
    enabled: true
    className: nginx
    host: backstage.apps.k8s.labjp.xyz
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"