backstage:
  image:
    repository: backstage/backstage
    tag: "1.31.0"

  backstage:
    appConfig:
      app:
        title: "eBPF + AI Security Portal"
        baseUrl: https://backstage.apps.k8s.labjp.xyz
        
      backend:
        baseUrl: https://backstage.apps.k8s.labjp.xyz
        cors:
          origin: https://backstage.apps.k8s.labjp.xyz
        database:
          client: better-sqlite3
          connection: ':memory:'

      auth:
        providers:
          guest:
            dangerouslyAllowOutsideDevelopment: true
        environment: development

      permission:
        enabled: false
        
      catalog:
        readonly: false
        refreshIntervalSeconds: 60
        providers:
          github:
            ebpf-ai-provider:
              organization: 'jeanlopezxyz'
              catalogPath: '/docs/catalog-info.yaml'
              filters:
                repository: 'ebpf-ia-kubernetes'
                branch: 'main'
              schedule:
                frequency: { minutes: 1 }
                timeout: { minutes: 3 }
        locations:
          - type: url
            target: https://github.com/jeanlopezxyz/ebpf-ia-kubernetes/blob/main/docs/catalog-info.yaml
        rules:
          - allow: [Component, System, API, Resource, Location]

      techdocs:
        builder: local
        generators:
          techdocs: local
        publisher:
          type: local


  postgresql:
    enabled: false


  ingress:
    enabled: true
    className: nginx
    host: backstage.apps.k8s.labjp.xyz
    path: /
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"