apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-admin-secret
  namespace: argocd
spec:
  encryptedData:
    mtime: AgB86JsN5+H6N8VOfwmG4+n6z/ZY6eoyegiLq0uX4IBQbEOjiTW4twi+t/Ok3luaO3a7OdwpLdg7iBd/PtaikO8j6Lqqtw49jldJNCgHw5W6HTh33Pj3HWq+or+2S9K1WcUL++qIWXCFPMrdhlSLiMs3H5zOoNPmB9q7lmvaiJtTuaGBGbCJ6hBGp1aF292o6QzK4lQ48YJIdNwoW3UZm/2jK4wqNATq3rxySLz9J2SfY9SXB4Ldp/reSttPByTCfKKtEdCW7lCXEssn9ZmQInWO8bRgYj5LvQ7srqcwdSp9divVrM2Cjrg6KxdGAso2QON/aER+k6iOYRCimgZmvmMCJzAxlhxTpjsF5/4fhWiBwjOe+NOn+k9rI1t7w9JekGSES54jH2MvqQBJFC60DqJ4BMGoNzPPdHWJEHvig+VX98md0MVtduSafPkoVQwlUrXZYUVCJNvCyEozc53gQ//sWQfjBmT1tLYXoLK59TKprEOCY5o5WJpkzc462WmtKmdLR9oHFGmS7Yf3WOAJRNA3wZa1uQYE6J40wbOt1vTMs/kIFXIDxygN1ue0HDHXfhXX1SDSuy3B3OyOjFcOZGXZaV9KmhlLoIeOTGhMPMgeHJyXXuYvK8GWkYbcvneialIsCw+TDoHD4yWDLVgiX3254Gyr5XlLvDpFBb+8wtr+LBYC2ZXU4tJ2DJ73bYDvQtAmv88+Ynu8qn4Z+zxrTjtE2OcCnw==
    password: AgByWJj4ivasZDXHT8bWMXY4BCSLxL5GiTLj+0i+tV2IQIAdVHWHh9MJQgwmxWx5zGBccV2u07cMJSwFZ5yrgvymUbfaHoxM2h8BOIMQOfN7csMIo06/NS55DhPfgMZfRbbcxGdm1jyW2F5uMz9Po1OyH4K3H5oFWljbMxoHvP5HOEEfvFBfOZ6DGckjhQ+bpjxYBdSs47vtn+7KfXdxvOy10/3v+BAbWtEl5Easl4Zr2cGyXB14AYZLKjb69kahj0J8JXxdd+2i0Y3PQgMM3MxGgyH0D2sdgMpeVXe7KUMquJV8PscN7GB4GgY+Z/TFxcGGoJjUXMIJwqWiHfxbapjtdoo4hRHoGdCLMcjK0YDlm0Xf6FKJfAC8yqGldt0OM4ZN7BEJl3vzVrsWzuAedBj+OODnvhLCkWZrace5FmTAVL7NjNEm4ZOacz0OWo5M6/YuYrLAA7GP9UTPQX3rDXcP3uoD/yMBeuwVROOcEsYU9FNVBiWktetP/ltMTIfOG1k+TM48MkS7fJdnb/NI4XZcTKzUZWRZsuTOiLb5Bdzmx7eG8ZkQeqglook4VNtbPDXrdOLMIm+0fj95Cst+MoeKSzD8WFM4Z+4ME5S8pVpCaYlibPnl75L8D3wKIhFFUqr2a92DBZTpdN66c6SR35lMzcrpJXpvFz0K9AbexBOEyP7JpN29KkLTWsRcQvosmBE8clVb5b0uuw5WjQQWwdtu+RE3JD2oPGYSWl92V3kbGkm4E1t9CQSbGyCMvP1hmfYdCoMzkO9edcWf7UI=
  template:
    metadata:
      creationTimestamp: null
      name: argocd-admin-secret
      namespace: argocd
---
